- project:
    check:
      jobs:
        - cyborg-devstack

- job:
    name: cyborg-devstack
    parent: legacy-dsvm-base
    run: playbooks/legacy/cyborg-devstack/run.yaml
    post-run: playbooks/legacy/cyborg-devstack/post.yaml
    timeout: 4200
    voting: false
    required-projects:
      - openstack-dev/devstack
      - openstack-infra/devstack-gate
      - openstack/cyborg
